package com.epam.jwd.web_app.controller.command;

public enum CommandName {
    LOGIN, REGISTER, LOGOUT, ADD_EDITION, DETAIL_EDITION, DETAIL_AUTHOR, LIST_EDITIONS, SEARCH, PAY, LIST_SUBSCRIPTIONS,
    DELETE_SUBSCRIBE, UNSUBSCRIBE, CREATE_POST, INDEX, UPDATE_USER, RESET_PASSWORD, DELETE_USER,
    DELETE_EDITION, POSTS_EDITION, DELETE_POST, CREATE_EDITION, CREDIT, LIST_SUBSCRIBE_CREDIT, BLOCK_USER, NO_SUCH
}